"""Shared API route constants for backend tests."""

ANALYSIS_ROOT = "/api/analysis/"
ANALYSIS_OPTIMIZE_RESUME = "/api/analysis/optimize-resume"
CONFIG_FIREBASE = "/api/config/firebase-config"
DOCUMENTS_ROOT = "/api/documents/"
GENKIT_COMPANY_CONTEXT = "/api/genkit/company/context"
GENKIT_COVER_LETTER = "/api/genkit/cover-letter/generate"
GENKIT_JOB_ANALYZE_URL = "/api/genkit/job/analyze-url"
GENKIT_KSC = "/api/genkit/ksc/generate"
GENKIT_RESUME_OPTIMIZE = "/api/genkit/resume/optimize"
LEGACY_INGEST = "/api/v1/ingest"
OPPORTUNITIES_ROOT = "/api/opportunities/"
WORKFLOWS_GENERATE_APPLICATION = "/api/workflows/generate-application"
