// Kerala Rage Tailwind Patch
// Auto-generated by scripts/build-m3-tokens.py
export default {
  theme: {
    extend: {
      colors: {
  "aboriginalFlagBlack": {
    "base": "var(--sys-color-aboriginalFlagBlack-base)",
    "steps": "var(--sys-color-aboriginalFlagBlack-steps)",
    "usage": "var(--sys-color-aboriginalFlagBlack-usage)"
  },
  "aboriginalFlagRed": {
    "base": "var(--sys-color-aboriginalFlagRed-base)",
    "steps": "var(--sys-color-aboriginalFlagRed-steps)",
    "usage": "var(--sys-color-aboriginalFlagRed-usage)"
  },
  "aboriginalFlagYellow": {
    "base": "var(--sys-color-aboriginalFlagYellow-base)",
    "steps": "var(--sys-color-aboriginalFlagYellow-steps)",
    "usage": "var(--sys-color-aboriginalFlagYellow-usage)"
  },
  "asphaltBlack": {
    "base": "var(--sys-color-asphaltBlack-base)",
    "steps": "var(--sys-color-asphaltBlack-steps)",
    "usage": "var(--sys-color-asphaltBlack-usage)"
  },
  "charcoalBackground": {
    "base": "var(--sys-color-charcoalBackground-base)",
    "steps": "var(--sys-color-charcoalBackground-steps)",
    "usage": "var(--sys-color-charcoalBackground-usage)"
  },
  "concreteGrey": {
    "base": "var(--sys-color-concreteGrey-base)",
    "steps": "var(--sys-color-concreteGrey-steps)",
    "usage": "var(--sys-color-concreteGrey-usage)"
  },
  "inkGold": {
    "base": "var(--sys-color-inkGold-base)",
    "steps": "var(--sys-color-inkGold-steps)",
    "usage": "var(--sys-color-inkGold-usage)"
  },
  "kr-activistSmokeGreen": {
    "base": "var(--sys-color-kr-activistSmokeGreen-base)",
    "steps": "var(--sys-color-kr-activistSmokeGreen-steps)",
    "usage": "var(--sys-color-kr-activistSmokeGreen-usage)"
  },
  "kr-charcoalRed": {
    "base": "var(--sys-color-kr-charcoalRed-base)",
    "steps": "var(--sys-color-kr-charcoalRed-steps)",
    "usage": "var(--sys-color-kr-charcoalRed-usage)"
  },
  "ochreEarth": {
    "base": "var(--sys-color-ochreEarth-base)",
    "steps": "var(--sys-color-ochreEarth-steps)",
    "usage": "var(--sys-color-ochreEarth-usage)"
  },
  "paperWhite": {
    "base": "var(--sys-color-paperWhite-base)",
    "steps": "var(--sys-color-paperWhite-steps)",
    "usage": "var(--sys-color-paperWhite-usage)"
  },
  "protestMetalBlue": {
    "base": "var(--sys-color-protestMetalBlue-base)",
    "steps": "var(--sys-color-protestMetalBlue-steps)",
    "usage": "var(--sys-color-protestMetalBlue-usage)"
  },
  "semantic": {
    "ash-grey": "var(--sys-color-semantic-ash-grey)",
    "parchment": "var(--sys-color-semantic-parchment)",
    "solidarity-crimson": "var(--sys-color-semantic-solidarity-crimson)",
    "solidarity-gold": "var(--sys-color-semantic-solidarity-gold)"
  },
  "signalGreen": {
    "base": "var(--sys-color-signalGreen-base)",
    "steps": "var(--sys-color-signalGreen-steps)",
    "usage": "var(--sys-color-signalGreen-usage)"
  },
  "solidarityRed": {
    "base": "var(--sys-color-solidarityRed-base)",
    "steps": "var(--sys-color-solidarityRed-steps)",
    "usage": "var(--sys-color-solidarityRed-usage)"
  },
  "solidaritySmokeOrange": {
    "base": "var(--sys-color-solidaritySmokeOrange-base)",
    "steps": "var(--sys-color-solidaritySmokeOrange-steps)",
    "usage": "var(--sys-color-solidaritySmokeOrange-usage)"
  },
  "stencilYellow": {
    "base": "var(--sys-color-stencilYellow-base)",
    "steps": "var(--sys-color-stencilYellow-steps)",
    "usage": "var(--sys-color-stencilYellow-usage)"
  },
  "worker-ash": {
    "base": "var(--sys-color-worker-ash-base)",
    "steps": "var(--sys-color-worker-ash-steps)",
    "usage": "var(--sys-color-worker-ash-usage)"
  }
},
      borderRadius: {
  "_comment": "var(--sys-shape-_comment)",
  "_comment_compat": "var(--sys-shape-_comment_compat)",
  "_comment_tension": "var(--sys-shape-_comment_tension)",
  "_comment_v61": "var(--sys-shape-_comment_v61)",
  "alertShard01": "var(--sys-shape-alertShard01)",
  "alertShard01-pressed": "var(--sys-shape-alertShard01-pressed)",
  "blob01": "var(--sys-shape-blob01)",
  "blob02": "var(--sys-shape-blob02)",
  "block01": "var(--sys-shape-block01)",
  "block02": "var(--sys-shape-block02)",
  "block03": "var(--sys-shape-block03)",
  "blockRiot01": "var(--sys-shape-blockRiot01)",
  "blockRiot01-pressed": "var(--sys-shape-blockRiot01-pressed)",
  "blockRiot02": "var(--sys-shape-blockRiot02)",
  "blockRiot03": "var(--sys-shape-blockRiot03)",
  "blockRiot03-loading": "var(--sys-shape-blockRiot03-loading)",
  "blockRiot03-pressed": "var(--sys-shape-blockRiot03-pressed)",
  "brickWall01": "var(--sys-shape-brickWall01)",
  "marchOpen": "var(--sys-shape-radius-marchOpen)",
  "marchOpen01": "var(--sys-shape-marchOpen01)",
  "marchSurge01": "var(--sys-shape-marchSurge01)",
  "marchSurge01-expanded": "var(--sys-shape-marchSurge01-expanded)",
  "megaphoneBase": "var(--sys-shape-radius-megaphoneBase)",
  "megaphoneBase01": "var(--sys-shape-megaphoneBase01)",
  "megaphoneCut01": "var(--sys-shape-megaphoneCut01)",
  "megaphoneCut01-loading": "var(--sys-shape-megaphoneCut01-loading)",
  "pebble": "var(--sys-shape-radius-marchOpen)",
  "pebble01": "var(--sys-shape-marchOpen01)",
  "pebbleSurge01": "var(--sys-shape-marchSurge01)",
  "pebbleSurge01-expanded": "var(--sys-shape-marchSurge01-expanded)",
  "pill01": "var(--sys-shape-pill01)",
  "pillMarch01": "var(--sys-shape-pillMarch01)",
  "pillMarch01-pressed": "var(--sys-shape-pillMarch01-pressed)",
  "placardBase": "var(--sys-shape-radius-placardBase)",
  "placardBase01": "var(--sys-shape-placardBase01)",
  "placardTorn01": "var(--sys-shape-placardTorn01)",
  "placardTorn01-selected": "var(--sys-shape-placardTorn01-selected)",
  "radius": "var(--sys-shape-radius)",
  "scaffoldFrame01": "var(--sys-shape-scaffoldFrame01)",
  "scaffoldFrame01-focus": "var(--sys-shape-scaffoldFrame01-focus)",
  "scaffoldSlab01": "var(--sys-shape-scaffoldFrame01)",
  "scaffoldSlab01-focus": "var(--sys-shape-scaffoldFrame01-focus)",
  "sentryAvatar": "var(--sys-shape-sentryAvatar)",
  "slab": "var(--sys-shape-radius-placardBase)",
  "slab01": "var(--sys-shape-placardBase01)",
  "stone": "var(--sys-shape-radius-megaphoneBase)",
  "stone01": "var(--sys-shape-megaphoneBase01)",
  "substrateTile01": "var(--sys-shape-substrateTile01)",
  "substrateTile01-hover": "var(--sys-shape-substrateTile01-hover)",
  "substrateTile02": "var(--sys-shape-substrateTile02)",
  "tearBanner01": "var(--sys-shape-tearBanner01)",
  "tornEdgeClipPath": "var(--sys-shape-tornEdgeClipPath)"
},
      boxShadow: {
  "elevation1Pebble": "var(--sys-shadow-elevation1Strike)",
  "elevation1Strike": "var(--sys-shadow-elevation1Strike)",
  "elevation2Placard": "var(--sys-shadow-elevation2Placard)",
  "elevation2Stone": "var(--sys-shadow-elevation2Placard)",
  "elevation3HoverLift": "var(--sys-shadow-elevation3HoverLift)",
  "elevation4Float": "var(--sys-shadow-elevation4Float)",
  "inkOffset": "var(--sys-shadow-inkOffset)",
  "solidarityBleed": "var(--sys-shadow-solidarityBleed)",
  "viscousBreezeTransition": "var(--sys-shadow-viscousBreezeTransition)"
},
      fontFamily: {
  "colorAccent": [
    "Nabla"
  ],
  "curator": [
    "Caveat"
  ],
  "display": [
    "Fraunces"
  ],
  "mono": [
    "JetBrains Mono"
  ],
  "primary": [
    "Work Sans"
  ],
  "proclamation": [
    "Libre Bodoni"
  ]
},
      fontSize: {
  "body": "var(--sys-type-scale-body)",
  "display": "var(--sys-type-scale-display)",
  "headline": "var(--sys-type-scale-headline)",
  "hero": "var(--sys-type-scale-hero)",
  "micro": "var(--sys-type-scale-micro)",
  "small": "var(--sys-type-scale-small)",
  "subhead": "var(--sys-type-scale-subhead)"
},
      transitionTimingFunction: {
        'm3-expressive': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'standard': 'cubic-bezier(0.2, 0, 0, 1)',
      },
      transitionDuration: {
        'short1': '100ms',
        'short2': '200ms',
        'medium1': '400ms',
        'long1': '600ms',
      }
    }
  }
};
