// Kerala Rage Tailwind Patch
// Auto-generated by scripts/build-m3-tokens.py
export default {
  theme: {
    extend: {
      colors: {
        "semantic": {
                "specimen-night": "var(--sys-color-semantic-specimen-night)",
                "wattle-gold": "var(--sys-color-semantic-wattle-gold)",
                "waratah-crimson": "var(--sys-color-semantic-waratah-crimson)",
                "flannel-flower": "var(--sys-color-semantic-flannel-flower)",
                "parchment": "var(--sys-color-semantic-parchment)"
        },
        "charcoalBackground": {
                "base": "var(--sys-color-charcoalBackground-base)",
                "steps-0": "var(--sys-color-charcoalBackground-steps-0)",
                "steps-1": "var(--sys-color-charcoalBackground-steps-1)",
                "steps-2": "var(--sys-color-charcoalBackground-steps-2)",
                "steps-3": "var(--sys-color-charcoalBackground-steps-3)",
                "steps-4": "var(--sys-color-charcoalBackground-steps-4)",
                "steps-5": "var(--sys-color-charcoalBackground-steps-5)",
                "steps-6": "var(--sys-color-charcoalBackground-steps-6)",
                "usage-0": "var(--sys-color-charcoalBackground-usage-0)",
                "usage-1": "var(--sys-color-charcoalBackground-usage-1)",
                "usage-2": "var(--sys-color-charcoalBackground-usage-2)",
                "usage-3": "var(--sys-color-charcoalBackground-usage-3)"
        },
        "solidarityRed": {
                "base": "var(--sys-color-solidarityRed-base)",
                "steps-0": "var(--sys-color-solidarityRed-steps-0)",
                "steps-1": "var(--sys-color-solidarityRed-steps-1)",
                "steps-2": "var(--sys-color-solidarityRed-steps-2)",
                "steps-3": "var(--sys-color-solidarityRed-steps-3)",
                "steps-4": "var(--sys-color-solidarityRed-steps-4)",
                "steps-5": "var(--sys-color-solidarityRed-steps-5)",
                "usage-0": "var(--sys-color-solidarityRed-usage-0)",
                "usage-1": "var(--sys-color-solidarityRed-usage-1)",
                "usage-2": "var(--sys-color-solidarityRed-usage-2)",
                "usage-3": "var(--sys-color-solidarityRed-usage-3)"
        },
        "kr-charcoalRed": {
                "base": "var(--sys-color-kr-charcoalRed-base)",
                "steps-0": "var(--sys-color-kr-charcoalRed-steps-0)",
                "steps-1": "var(--sys-color-kr-charcoalRed-steps-1)",
                "steps-2": "var(--sys-color-kr-charcoalRed-steps-2)",
                "steps-3": "var(--sys-color-kr-charcoalRed-steps-3)",
                "steps-4": "var(--sys-color-kr-charcoalRed-steps-4)",
                "steps-5": "var(--sys-color-kr-charcoalRed-steps-5)",
                "usage-0": "var(--sys-color-kr-charcoalRed-usage-0)",
                "usage-1": "var(--sys-color-kr-charcoalRed-usage-1)",
                "usage-2": "var(--sys-color-kr-charcoalRed-usage-2)",
                "usage-3": "var(--sys-color-kr-charcoalRed-usage-3)"
        },
        "kr-activistSmokeGreen": {
                "base": "var(--sys-color-kr-activistSmokeGreen-base)",
                "steps-0": "var(--sys-color-kr-activistSmokeGreen-steps-0)",
                "steps-1": "var(--sys-color-kr-activistSmokeGreen-steps-1)",
                "steps-2": "var(--sys-color-kr-activistSmokeGreen-steps-2)",
                "steps-3": "var(--sys-color-kr-activistSmokeGreen-steps-3)",
                "steps-4": "var(--sys-color-kr-activistSmokeGreen-steps-4)",
                "steps-5": "var(--sys-color-kr-activistSmokeGreen-steps-5)",
                "steps-6": "var(--sys-color-kr-activistSmokeGreen-steps-6)",
                "usage-0": "var(--sys-color-kr-activistSmokeGreen-usage-0)",
                "usage-1": "var(--sys-color-kr-activistSmokeGreen-usage-1)",
                "usage-2": "var(--sys-color-kr-activistSmokeGreen-usage-2)",
                "usage-3": "var(--sys-color-kr-activistSmokeGreen-usage-3)"
        },
        "signalGreen": {
                "base": "var(--sys-color-signalGreen-base)",
                "steps-0": "var(--sys-color-signalGreen-steps-0)",
                "steps-1": "var(--sys-color-signalGreen-steps-1)",
                "steps-2": "var(--sys-color-signalGreen-steps-2)",
                "steps-3": "var(--sys-color-signalGreen-steps-3)",
                "steps-4": "var(--sys-color-signalGreen-steps-4)",
                "steps-5": "var(--sys-color-signalGreen-steps-5)",
                "steps-6": "var(--sys-color-signalGreen-steps-6)",
                "usage-0": "var(--sys-color-signalGreen-usage-0)",
                "usage-1": "var(--sys-color-signalGreen-usage-1)",
                "usage-2": "var(--sys-color-signalGreen-usage-2)",
                "usage-3": "var(--sys-color-signalGreen-usage-3)"
        },
        "inkGold": {
                "base": "var(--sys-color-inkGold-base)",
                "steps-0": "var(--sys-color-inkGold-steps-0)",
                "steps-1": "var(--sys-color-inkGold-steps-1)",
                "steps-2": "var(--sys-color-inkGold-steps-2)",
                "steps-3": "var(--sys-color-inkGold-steps-3)",
                "steps-4": "var(--sys-color-inkGold-steps-4)",
                "steps-5": "var(--sys-color-inkGold-steps-5)",
                "steps-6": "var(--sys-color-inkGold-steps-6)",
                "usage-0": "var(--sys-color-inkGold-usage-0)",
                "usage-1": "var(--sys-color-inkGold-usage-1)",
                "usage-2": "var(--sys-color-inkGold-usage-2)",
                "usage-3": "var(--sys-color-inkGold-usage-3)"
        },
        "stencilYellow": {
                "base": "var(--sys-color-stencilYellow-base)",
                "steps-0": "var(--sys-color-stencilYellow-steps-0)",
                "steps-1": "var(--sys-color-stencilYellow-steps-1)",
                "steps-2": "var(--sys-color-stencilYellow-steps-2)",
                "steps-3": "var(--sys-color-stencilYellow-steps-3)",
                "steps-4": "var(--sys-color-stencilYellow-steps-4)",
                "steps-5": "var(--sys-color-stencilYellow-steps-5)",
                "steps-6": "var(--sys-color-stencilYellow-steps-6)",
                "usage-0": "var(--sys-color-stencilYellow-usage-0)",
                "usage-1": "var(--sys-color-stencilYellow-usage-1)",
                "usage-2": "var(--sys-color-stencilYellow-usage-2)",
                "usage-3": "var(--sys-color-stencilYellow-usage-3)"
        },
        "worker-ash": {
                "base": "var(--sys-color-worker-ash-base)",
                "steps-0": "var(--sys-color-worker-ash-steps-0)",
                "steps-1": "var(--sys-color-worker-ash-steps-1)",
                "steps-2": "var(--sys-color-worker-ash-steps-2)",
                "steps-3": "var(--sys-color-worker-ash-steps-3)",
                "steps-4": "var(--sys-color-worker-ash-steps-4)",
                "steps-5": "var(--sys-color-worker-ash-steps-5)",
                "steps-6": "var(--sys-color-worker-ash-steps-6)",
                "usage-0": "var(--sys-color-worker-ash-usage-0)",
                "usage-1": "var(--sys-color-worker-ash-usage-1)",
                "usage-2": "var(--sys-color-worker-ash-usage-2)",
                "usage-3": "var(--sys-color-worker-ash-usage-3)"
        },
        "solidaritySmokeOrange": {
                "base": "var(--sys-color-solidaritySmokeOrange-base)",
                "steps-0": "var(--sys-color-solidaritySmokeOrange-steps-0)",
                "steps-1": "var(--sys-color-solidaritySmokeOrange-steps-1)",
                "steps-2": "var(--sys-color-solidaritySmokeOrange-steps-2)",
                "steps-3": "var(--sys-color-solidaritySmokeOrange-steps-3)",
                "steps-4": "var(--sys-color-solidaritySmokeOrange-steps-4)",
                "steps-5": "var(--sys-color-solidaritySmokeOrange-steps-5)",
                "steps-6": "var(--sys-color-solidaritySmokeOrange-steps-6)",
                "usage-0": "var(--sys-color-solidaritySmokeOrange-usage-0)",
                "usage-1": "var(--sys-color-solidaritySmokeOrange-usage-1)",
                "usage-2": "var(--sys-color-solidaritySmokeOrange-usage-2)",
                "usage-3": "var(--sys-color-solidaritySmokeOrange-usage-3)"
        },
        "labWrenMetalBlue": {
                "base": "var(--sys-color-labWrenMetalBlue-base)",
                "steps-0": "var(--sys-color-labWrenMetalBlue-steps-0)",
                "steps-1": "var(--sys-color-labWrenMetalBlue-steps-1)",
                "steps-2": "var(--sys-color-labWrenMetalBlue-steps-2)",
                "steps-3": "var(--sys-color-labWrenMetalBlue-steps-3)",
                "steps-4": "var(--sys-color-labWrenMetalBlue-steps-4)",
                "steps-5": "var(--sys-color-labWrenMetalBlue-steps-5)",
                "steps-6": "var(--sys-color-labWrenMetalBlue-steps-6)",
                "usage-0": "var(--sys-color-labWrenMetalBlue-usage-0)",
                "usage-1": "var(--sys-color-labWrenMetalBlue-usage-1)",
                "usage-2": "var(--sys-color-labWrenMetalBlue-usage-2)",
                "usage-3": "var(--sys-color-labWrenMetalBlue-usage-3)"
        },
        "aboriginalFlagRed": {
                "base": "var(--sys-color-aboriginalFlagRed-base)",
                "steps-0": "var(--sys-color-aboriginalFlagRed-steps-0)",
                "steps-1": "var(--sys-color-aboriginalFlagRed-steps-1)",
                "steps-2": "var(--sys-color-aboriginalFlagRed-steps-2)",
                "steps-3": "var(--sys-color-aboriginalFlagRed-steps-3)",
                "steps-4": "var(--sys-color-aboriginalFlagRed-steps-4)",
                "steps-5": "var(--sys-color-aboriginalFlagRed-steps-5)",
                "usage-0": "var(--sys-color-aboriginalFlagRed-usage-0)",
                "usage-1": "var(--sys-color-aboriginalFlagRed-usage-1)"
        },
        "aboriginalFlagYellow": {
                "base": "var(--sys-color-aboriginalFlagYellow-base)",
                "steps-0": "var(--sys-color-aboriginalFlagYellow-steps-0)",
                "steps-1": "var(--sys-color-aboriginalFlagYellow-steps-1)",
                "steps-2": "var(--sys-color-aboriginalFlagYellow-steps-2)",
                "steps-3": "var(--sys-color-aboriginalFlagYellow-steps-3)",
                "steps-4": "var(--sys-color-aboriginalFlagYellow-steps-4)",
                "steps-5": "var(--sys-color-aboriginalFlagYellow-steps-5)",
                "usage-0": "var(--sys-color-aboriginalFlagYellow-usage-0)",
                "usage-1": "var(--sys-color-aboriginalFlagYellow-usage-1)"
        },
        "aboriginalFlagBlack": {
                "base": "var(--sys-color-aboriginalFlagBlack-base)",
                "steps-0": "var(--sys-color-aboriginalFlagBlack-steps-0)",
                "steps-1": "var(--sys-color-aboriginalFlagBlack-steps-1)",
                "steps-2": "var(--sys-color-aboriginalFlagBlack-steps-2)",
                "steps-3": "var(--sys-color-aboriginalFlagBlack-steps-3)",
                "steps-4": "var(--sys-color-aboriginalFlagBlack-steps-4)",
                "usage-0": "var(--sys-color-aboriginalFlagBlack-usage-0)",
                "usage-1": "var(--sys-color-aboriginalFlagBlack-usage-1)"
        },
        "asphaltBlack": {
                "base": "var(--sys-color-asphaltBlack-base)",
                "steps-0": "var(--sys-color-asphaltBlack-steps-0)",
                "steps-1": "var(--sys-color-asphaltBlack-steps-1)",
                "steps-2": "var(--sys-color-asphaltBlack-steps-2)",
                "steps-3": "var(--sys-color-asphaltBlack-steps-3)",
                "steps-4": "var(--sys-color-asphaltBlack-steps-4)",
                "usage-0": "var(--sys-color-asphaltBlack-usage-0)",
                "usage-1": "var(--sys-color-asphaltBlack-usage-1)",
                "usage-2": "var(--sys-color-asphaltBlack-usage-2)"
        },
        "concreteGrey": {
                "base": "var(--sys-color-concreteGrey-base)",
                "steps-0": "var(--sys-color-concreteGrey-steps-0)",
                "steps-1": "var(--sys-color-concreteGrey-steps-1)",
                "steps-2": "var(--sys-color-concreteGrey-steps-2)",
                "steps-3": "var(--sys-color-concreteGrey-steps-3)",
                "steps-4": "var(--sys-color-concreteGrey-steps-4)",
                "usage-0": "var(--sys-color-concreteGrey-usage-0)",
                "usage-1": "var(--sys-color-concreteGrey-usage-1)",
                "usage-2": "var(--sys-color-concreteGrey-usage-2)",
                "usage-3": "var(--sys-color-concreteGrey-usage-3)"
        },
        "gumLeafGreen": {
                "base": "var(--sys-color-gumLeafGreen-base)",
                "steps-0": "var(--sys-color-gumLeafGreen-steps-0)",
                "steps-1": "var(--sys-color-gumLeafGreen-steps-1)",
                "steps-2": "var(--sys-color-gumLeafGreen-steps-2)",
                "steps-3": "var(--sys-color-gumLeafGreen-steps-3)",
                "steps-4": "var(--sys-color-gumLeafGreen-steps-4)",
                "usage-0": "var(--sys-color-gumLeafGreen-usage-0)",
                "usage-1": "var(--sys-color-gumLeafGreen-usage-1)",
                "usage-2": "var(--sys-color-gumLeafGreen-usage-2)"
        },
        "ochreEarth": {
                "base": "var(--sys-color-ochreEarth-base)",
                "steps-0": "var(--sys-color-ochreEarth-steps-0)",
                "steps-1": "var(--sys-color-ochreEarth-steps-1)",
                "steps-2": "var(--sys-color-ochreEarth-steps-2)",
                "steps-3": "var(--sys-color-ochreEarth-steps-3)",
                "steps-4": "var(--sys-color-ochreEarth-steps-4)",
                "usage-0": "var(--sys-color-ochreEarth-usage-0)",
                "usage-1": "var(--sys-color-ochreEarth-usage-1)",
                "usage-2": "var(--sys-color-ochreEarth-usage-2)"
        },
        "paperWhite": {
                "base": "var(--sys-color-paperWhite-base)",
                "steps-0": "var(--sys-color-paperWhite-steps-0)",
                "steps-1": "var(--sys-color-paperWhite-steps-1)",
                "steps-2": "var(--sys-color-paperWhite-steps-2)",
                "steps-3": "var(--sys-color-paperWhite-steps-3)",
                "steps-4": "var(--sys-color-paperWhite-steps-4)",
                "usage-0": "var(--sys-color-paperWhite-usage-0)",
                "usage-1": "var(--sys-color-paperWhite-usage-1)",
                "usage-2": "var(--sys-color-paperWhite-usage-2)"
        }
},
      borderRadius: {
        "stone": "var(--sys-shape-radius-stone)",
        "slab": "var(--sys-shape-radius-slab)",
        "pebble": "var(--sys-shape-radius-pebble)",
        "sentryAvatar": "var(--sys-shape-sentryAvatar)",
        "tornEdgeClipPath": "var(--sys-shape-tornEdgeClipPath)"
},
      boxShadow: {
        "elevation1Pebble": "var(--sys-shadow-elevation1Pebble)",
        "elevation2Stone": "var(--sys-shadow-elevation2Stone)",
        "elevation3HoverLift": "var(--sys-shadow-elevation3HoverLift)",
        "elevation4Float": "var(--sys-shadow-elevation4Float)",
        "inkOffset": "var(--sys-shadow-inkOffset)",
        "solidarityBleed": "var(--sys-shadow-solidarityBleed)",
        "viscousBreezeTransition": "var(--sys-shadow-viscousBreezeTransition)"
},
      fontFamily: {
        "primary": [
                "Work Sans"
        ],
        "display": [
                "Fraunces"
        ],
        "proclamation": [
                "Libre Bodoni"
        ],
        "mono": [
                "JetBrains Mono"
        ],
        "curator": [
                "Caveat"
        ],
        "colorAccent": [
                "Nabla"
        ]
},
      fontSize: {
        "micro": "var(--sys-type-scale-micro)",
        "small": "var(--sys-type-scale-small)",
        "body": "var(--sys-type-scale-body)",
        "subhead": "var(--sys-type-scale-subhead)",
        "headline": "var(--sys-type-scale-headline)",
        "display": "var(--sys-type-scale-display)",
        "hero": "var(--sys-type-scale-hero)"
},
      transitionTimingFunction: {
        'm3-expressive': 'cubic-bezier(0.34, 1.56, 0.64, 1)',
        'standard': 'cubic-bezier(0.2, 0, 0, 1)',
      },
      transitionDuration: {
        'short1': '100ms',
        'short2': '200ms',
        'medium1': '400ms',
        'long1': '600ms',
      }
    }
  }
};