/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "vwtadxxtpnbwpdhjmpbu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3dGFkeHh0cG5id3BkaGptcGJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgxODg3NTUsImV4cCI6MjA4Mzc2NDc1NX0.UbsZquq_NVOgKlmWq0mgjM-psO1RdHip8aLJklv6sWw"
