# 📚 PROJECT KNOWLEDGE BASE INDEX (CRITICAL CONTEXT)

This file serves as the definitive index to all project standards, agents, and automation scripts. **DO NOT** use detailed information from this file; **ALWAYS** consult the indexed reference documents and skills when performing tasks.

---

## 1. 🏗️ CORE ARCHITECTURE & STACK

* **Frontend:** React 18.2.0 + TypeScript 5.0+ (Vite). Styling: Material-UI v5.18, Emotion, Tailwind CSS.
* **Backend:** Python (FastAPI/Genkit) and Firebase Functions (Node.js 20).
* **Database/Cache:** Firebase Cloud Firestore (Primary DB and cache collection `redis_cache`).
* **Primary Region:** `us-central1` for all infrastructure (Functions, Firestore, Cloud Run).
* **Type Safety:** **CRITICAL**: Type consistency **MUST** be maintained across the full stack (TS interfaces ↔ Pydantic models).

## 2. 🤖 AI AGENTS & SKILLS INDEX (The Automation Layer)

Use these skills and agents for all automation and complex task execution.

### Agents (Orchestrators)
| Agent Name | Expertise | Index File | When to Use |
| :--- | :--- | :--- | :--- |
| **fullstack-integration-specialist** | Full stack feature planning & debugging. | `.claude/agents/fullstack-integration-specialist.md` | Integration issues, new feature planning. |
| **m3-migration-architect** | Orchestrates 12-step M3 Expressive migration. | `.claude/agents/m3-migration-architect.md` | Component migration to M3 Expressive. |
| **testing-specialist** | Coordinates all test generation and coverage analysis. | *(Implicit, references skills)* | Generating new tests or analyzing coverage. |
| **Visual Design Director** | Defines aesthetic direction, M3 Anti-Slop validation. | `.claude/agents/visual-design-director.md` | Defining design tokens or auditing aesthetics. |
| **gemini-wrapper** | Delegates specialized tasks (analysis, summarization) to Gemini 1.5-Flash models. | `.claude/interfaces/gemini-wrapper-interface.py` | Code analysis, brainstorming, error diagnosis, documentation analysis. |

### Skill Libraries (Full Index in Dedicated File)
* **Full Skill Index & Capabilities:** `docs/architecture/SKILL_AGENT_MATRIX.md` (See this for all 30+ skills).
* **Key Skill Sets:** Scaffolding, Testing, M3 Expressive. (All details in `docs/architecture/SKILL_AGENT_MATRIX.md`)

---

## 3. 🚨 AGENT WORKFLOW HYGIENE (Efficiency Rules)

These rules are non-negotiable for maintaining high context quality and low operational cost.

* **R1: Context Clearing:** Use the `/clear` command after **every 1-3 messages** or upon task completion to prevent context bloat. This is essential for agent focus.
* **R2: Auto-Compact:** **YOU MUST** verify that Auto-compact is **DISABLED** in the `/config` settings to prevent old sessions from consuming token space.
* **R3: Planning Mandate:** For any task involving **more than one file** or a core architectural change, the agent **MUST** generate a plan before writing code (`Plan-then-Execute` workflow).

---

## 4. ⚙️ WORKFLOW & COMMAND REFERENCES

| Area | Quick Start Script / Command | Detailed Documentation |
| :--- | :--- | :--- |
| **Deployment** | `./scripts/deploy.sh` (staging/production) | `docs/DEPLOYMENT_WORKFLOW.md` |
| **Secrets Setup** | `./scripts/setup-secrets.sh` (unified) | `docs/SECRETS_MANAGEMENT.md` |
| **Linting/Formatting**| `yarn lint:fix` (auto-fix) | `.vscode/settings.json` (Auto-fix on save) |
| **Email Service** | `AWS_SES_QUICK_START.md` | `docs/AWS_SES_SETUP.md` |
| **M3 Prep Steps** | `./scripts/prepare-for-migration.sh` | `docs/MIGRATION_READINESS.md` |
| **Jules Delegation** | `cat tasks.txt \| while ...` (Launch all) | `docs/JULES_PROTOCOL.md` |

---

## 5. 🛑 CRITICAL CONSTRAINTS & DEVELOPMENT GUIDELINES

* **Paths:** All paths must be **relative** (start with `./`).
* **Commit Messages:** **MUST** use Conventional Commits (e.g., `feat:`, `fix:`, `chore:`).
* **Testing:** Frontend (Jest), Backend (pytest), E2E (Playwright). **NEVER** merge without passing CI.
* **M3 Anti-Slop:** Aesthetic score **MUST** be $\geq 80$. Do not use generic fonts (Inter, Roboto, Arial).
* **Error Handling:** All async functions **MUST** include robust `try...catch` blocks.

---

## 6. 📊 Status & Reports

* **Test Coverage:** Frontend 17%, Backend 85%, E2E 90% (Target: 50% / 95% / 95%).
* **M3 Readiness:** 12% (Target: 70%).
* **Full Audit Report:** `docs/architecture/AGENT_SYSTEM_REFERENCE.md` (Complete agent reference).
* **Integration Health Report:** `docs/INTEGRATION_MAP.md` (Generated by `frontend-backend-mapper` skill).
