#!/usr/bin/env python3
"""
Fetch Firebase configuration from Secret Manager for build process.

This script retrieves Firebase configuration from Google Cloud Secret Manager
and creates the appropriate environment file for the frontend build process.
"""

import os
import sys
from pathlib import Path

# Add the backend directory to the Python path
sys.path.insert(0, str(Path(__file__).parent.parent / "backend"))

from app.core.secret_manager import get_firebase_frontend_config


def create_frontend_env_file(output_path: str, environment: str = "production"):
    """
    Create frontend environment file with Firebase configuration from Secret Manager.

    Args:
        output_path: Path where to create the .env file
        environment: Environment name (production, staging, development)
    """
    try:
        # Get Firebase configuration from Secret Manager
        firebase_config = get_firebase_frontend_config()

        # Validate configuration
        required_fields = ["api_key", "auth_domain", "project_id", "storage_bucket"]
        missing_fields = [field for field in required_fields if not firebase_config.get(field)]

        if missing_fields:
            print(f"❌ Missing required Firebase configuration: {', '.join(missing_fields)}")
            return False

        # Create environment file content
        env_content = f"""# Firebase Configuration from Secret Manager
# Generated by fetch-firebase-config.py
# Environment: {environment}

VITE_FIREBASE_API_KEY={firebase_config['api_key']}
VITE_FIREBASE_AUTH_DOMAIN={firebase_config['auth_domain']}
VITE_FIREBASE_PROJECT_ID={firebase_config['project_id']}
VITE_FIREBASE_STORAGE_BUCKET={firebase_config['storage_bucket']}
VITE_FIREBASE_MESSAGING_SENDER_ID={firebase_config['messaging_sender_id']}
VITE_FIREBASE_APP_ID={firebase_config['app_id']}

# Environment specific settings
VITE_ENVIRONMENT={environment}
"""

        # Write the file
        output_dir = os.path.dirname(output_path)
        if output_dir:  # Only create directory if there is a directory component
            os.makedirs(output_dir, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(env_content)

        print(f"✅ Created Firebase environment file: {output_path}")
        print(f"   Environment: {environment}")
        print(f"   Project ID: {firebase_config['project_id']}")
        print(f"   Auth Domain: {firebase_config['auth_domain']}")

        return True

    except Exception as e:
        print(f"❌ Error creating environment file: {e}")
        return False


def main():
    """Main function."""
    import argparse

    parser = argparse.ArgumentParser(
        description="Fetch Firebase configuration from Secret Manager"
    )
    parser.add_argument(
        "--output", "-o",
        default="frontend/.env.production.local",
        help="Output path for the environment file"
    )
    parser.add_argument(
        "--environment", "-e",
        default="production",
        choices=["production", "staging", "development"],
        help="Environment name"
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help="Only validate configuration, don't create file"
    )

    args = parser.parse_args()

    print("🔧 Firebase Configuration Fetcher")
    print("=================================")

    if args.validate_only:
        print("📋 Validating Firebase configuration...")
        try:
            config = get_firebase_frontend_config()
            required_fields = ["api_key", "auth_domain", "project_id", "storage_bucket"]
            missing_fields = [field for field in required_fields if not config.get(field)]

            if missing_fields:
                print(f"❌ Missing configuration: {', '.join(missing_fields)}")
                sys.exit(1)
            else:
                print("✅ Firebase configuration is complete")
                for field in required_fields:
                    print(f"   {field}: {'✓' if config.get(field) else '✗'}")
                sys.exit(0)

        except Exception as e:
            print(f"❌ Error validating configuration: {e}")
            sys.exit(1)

    # Create the environment file
    success = create_frontend_env_file(args.output, args.environment)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
