from typing import Any, Callable, Dict, List, Optional, Type, TypeVar, Union, overload

from typing_extensions import Protocol, runtime_checkable

T = TypeVar("T")
T_co = TypeVar("T_co", covariant=True)

class DeclarativeBase:
    __table__: Any
    __tablename__: str

    @classmethod
    def __declare_last__(cls) -> None: ...
    @classmethod
    def __declare_first__(cls) -> None: ...

class Mapped(Protocol[T_co]):
    """A type that may be used to indicate any ORM-mapped type."""

class Column(Protocol[T_co]):
    """Type for SQLAlchemy Column"""

    def __init__(
        self,
        type_: Type[T],
        *,
        primary_key: bool = False,
        nullable: bool = True,
        default: Any = None,
        unique: bool = False,
        index: bool = False,
        **kwargs: Any,
    ) -> None: ...

class relationship(Protocol[T_co]):
    """Type for SQLAlchemy relationship"""

    def __init__(
        self,
        argument: Optional[Union[Type[T], str]] = None,
        secondary: Any = None,
        back_populates: Optional[str] = None,
        backref: Optional[str] = None,
        lazy: str = "select",
        **kwargs: Any,
    ) -> None: ...

class declared_attr(Protocol):
    """Type for SQLAlchemy declared_attr"""

    def __init__(self, fget: Callable[..., T]) -> None: ...

class ForeignKey:
    """Type for SQLAlchemy ForeignKey"""

    def __init__(self, column: str, **kwargs: Any) -> None: ...

class Integer: ...

class String:
    def __init__(self, length: Optional[int] = None, **kwargs: Any) -> None: ...

class Text: ...
class Boolean: ...
class DateTime: ...
class JSON: ...
class Float: ...

class Enum:
    def __init__(self, *enums: str, **kwargs: Any) -> None: ...

# ORM specific types
class Query(Protocol[T]):
    def filter(self, *criterion: Any) -> "Query[T]": ...
    def filter_by(self, **kwargs: Any) -> "Query[T]": ...
    def first(self) -> Optional[T]: ...
    def all(self) -> List[T]: ...
    def one(self) -> T: ...
    def one_or_none(self) -> Optional[T]: ...
    def count(self) -> int: ...
    def order_by(self, *criterion: Any) -> "Query[T]": ...
    def limit(self, limit: int) -> "Query[T]": ...
    def offset(self, offset: int) -> "Query[T]": ...
    def join(self, *props: Any, **kwargs: Any) -> "Query[T]": ...
    def outerjoin(self, *props: Any, **kwargs: Any) -> "Query[T]": ...
    def group_by(self, *criterion: Any) -> "Query[T]": ...
    def having(self, criterion: Any) -> "Query[T]": ...
    def distinct(self, *criterion: Any) -> "Query[T]": ...

class Session(Protocol):
    def add(self, instance: Any) -> None: ...
    def add_all(self, instances: List[Any]) -> None: ...
    def delete(self, instance: Any) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def query(self, *entities: Any, **kwargs: Any) -> Query[Any]: ...
    def execute(
        self, statement: Any, params: Optional[Dict[str, Any]] = None, **kwargs: Any
    ) -> Any: ...
    def get(self, entity: Type[T], ident: Any) -> Optional[T]: ...
    def merge(self, instance: T, load: bool = True) -> T: ...
    def refresh(
        self,
        instance: Any,
        attribute_names: Optional[List[str]] = None,
        with_for_update: Optional[bool] = None,
    ) -> None: ...
    def expunge(self, instance: Any) -> None: ...
    def expunge_all(self) -> None: ...
    def is_modified(self, instance: Any, include_collections: bool = True) -> bool: ...
    def begin(self) -> Any: ...
    def begin_nested(self) -> Any: ...

# SQLAlchemy core types
class Table(Protocol):
    name: str
    columns: Any

    def __getitem__(self, key: str) -> Any: ...

class MetaData(Protocol):
    def create_all(
        self, bind: Any, tables: Optional[List[Table]] = None, checkfirst: bool = True
    ) -> None: ...
    def drop_all(
        self, bind: Any, tables: Optional[List[Table]] = None, checkfirst: bool = True
    ) -> None: ...
    def reflect(self, bind: Any, **kwargs: Any) -> None: ...

# Type variables for generic functions
_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

# Additional utility types
class EnumType(Protocol):
    """Protocol for SQLAlchemy Enum types"""

    def __init__(self, *enums: str, **kwargs: Any) -> None: ...

class TypeDecorator(Protocol):
    """Base class for custom type decorators"""

    impl: Any

    def process_bind_param(self, value: Any, dialect: Any) -> Any: ...
    def process_result_value(self, value: Any, dialect: Any) -> Any: ...
    def copy(self, **kw: Any) -> "TypeDecorator": ...
