#!/usr/bin/env python3
# scripts/build-design-tokens.py
import json
import os
import sys

# Define I/O paths
TOKEN_SOURCE_DIR = 'design-system'
TOKEN_SOURCE_FILE = os.path.join(TOKEN_SOURCE_DIR, 'tokens.json')
CSS_OUTPUT_FILE = 'frontend/src/styles/design-tokens.css'
TAILWIND_CONFIG_PATCH = os.path.join(TOKEN_SOURCE_DIR, 'tailwind-token-patch.js')

def load_tokens():
    """Loads the source JSON tokens."""
    print(f"Loading design tokens from {TOKEN_SOURCE_FILE}...")
    if not os.path.exists(TOKEN_SOURCE_FILE):
        print(f"Error: Token source file not found at {TOKEN_SOURCE_FILE}")
        print("Please run the 'design-token-generator' skill and save its output first.")
        return None
    with open(TOKEN_SOURCE_FILE, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON in token file. {e}")
            sys.exit(1)


def generate_css_variables(tokens):
    """Generates a CSS file with all tokens as CSS variables."""
    print(f"Generating CSS variables at {CSS_OUTPUT_FILE}...")

    # Ensure directory exists
    os.makedirs(os.path.dirname(CSS_OUTPUT_FILE), exist_ok=True)

    content = [
        "/* This file is auto-generated by 'scripts/build-design-tokens.py' */\n",
        "/* Do not edit this file directly. */\n",
        ":root {\n"
    ]

    # Add Colors
    for key, value in tokens.get('color', {}).items():
        content.append(f"  --sys-color-{key.replace('_', '-')}: {value};\n")

    # Add Shapes (Border Radius)
    for key, value in tokens.get('shape', {}).items():
        content.append(f"  --sys-shape-{key.replace('_', '-')}: {value};\n")

    # Add Spacing
    for key, value in tokens.get('spacing', {}).get('scale', {}).items():
        content.append(f"  --sys-space-{key.replace('space', '')}: {value};\n")

    # Add Elevation (Shadows)
    for key, value in tokens.get('elevation', {}).items():
        content.append(f"  --sys-elevation-{key.replace('_', '-')}: {value};\n")

    # Add Typography (Font Families)
    if tokens.get('typography', {}).get('fontFamilyBase'):
        content.append(f"  --sys-font-base: {tokens['typography']['fontFamilyBase']};\n")
    if tokens.get('typography', {}).get('fontFamilyHeading'):
        content.append(f"  --sys-font-heading: {tokens['typography']['fontFamilyHeading']};\n")

    # Add Typography (Font Scale)
    for key, value in tokens.get('typography', {}).get('scale', {}).items():
        content.append(f"  --sys-text-{key.replace('text', '')}: {value};\n")

    content.append("}\n")

    with open(CSS_OUTPUT_FILE, 'w') as f:
        f.writelines(content)
    print("✅ CSS variables file generated.")

def generate_tailwind_patch(tokens):
    """Generates a JS module to patch tailwind.config.js."""
    print(f"Generating Tailwind config patch at {TAILWIND_CONFIG_PATCH}...")

    # Ensure directory exists
    os.makedirs(os.path.dirname(TAILWIND_CONFIG_PATCH), exist_ok=True)

    # Map token names to Tailwind's config structure
    tailwind_colors = {key.replace('_', '-'): f"var(--sys-color-{key.replace('_', '-')})" for key in tokens.get('color', {})}
    tailwind_spacing = {key.replace('space', ''): value for key, value in tokens.get('spacing', {}).get('scale', {})}
    tailwind_shadows = {key.replace('_', '-'): value for key, value in tokens.get('elevation', {})}
    tailwind_radius = {key.replace('_', '-'): value for key, value in tokens.get('shape', {})}
    tailwind_fonts = {
        'base': [f"var(--sys-font-base)"],
        'heading': [f"var(--sys-font-heading)"],
    }
    tailwind_font_sizes = {key.replace('text', ''): value for key, value in tokens.get('typography', {}).get('scale', {})}

    patch_content = f"""
// This file is auto-generated by 'scripts/build-design-tokens.py'
// Do not edit this file directly.
// To update tokens, edit 'design-system/tokens.json' and run the script.

module.exports = {{
  theme: {{
    extend: {{
      colors: {{
        ...{json.dumps(tailwind_colors, indent=10)}
      }},
      spacing: {{
        ...{json.dumps(tailwind_spacing, indent=10)}
      }},
      boxShadow: {{
        ...{json.dumps(tailwind_shadows, indent=10)}
      }},
      borderRadius: {{
        ...{json.dumps(tailwind_radius, indent=10)}
      }},
      fontFamily: {{
        ...{json.dumps(tailwind_fonts, indent=10)}
      }},
      fontSize: {{
        ...{json.dumps(tailwind_font_sizes, indent=10)}
      }}
    }}
  }}
}};
"""
    with open(TAILWIND_CONFIG_PATCH, 'w') as f:
        f.write(patch_content)
    print("✅ Tailwind config patch generated.")
    print("\nTo use, merge this with your main tailwind.config.js")

if __name__ == "__main__":
    tokens = load_tokens()
    if tokens:
        generate_css_variables(tokens)
        generate_tailwind_patch(tokens)
        print("\n✨ Design token build complete.")
