#!/usr/bin/env python3
# scripts/build-m3-tokens.py
"""
Build Kerala Rage design tokens into CSS variables and Tailwind configuration.
"""
import json
import os
import sys

# Define I/O paths (Kerala Rage locations)
TOKEN_SOURCE_FILE = 'frontend/src/design/tokens/tokens.json'
CSS_OUTPUT_FILE = 'frontend/src/design/styles/design-tokens.css'
TAILWIND_CONFIG_PATCH = 'frontend/tailwind-m3-patch.js'

def load_tokens():
    """Loads the Kerala Rage JSON tokens."""
    print(f"Loading tokens from {TOKEN_SOURCE_FILE}...")
    if not os.path.exists(TOKEN_SOURCE_FILE):
        print(f"Error: Token source file not found at {TOKEN_SOURCE_FILE}")
        return None
    with open(TOKEN_SOURCE_FILE, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON in token file. {e}")
            sys.exit(1)

def resolve_values(node):
    """Recursively extracts $value from DTCG nodes."""
    if isinstance(node, dict):
        if '$value' in node:
            return resolve_values(node['$value'])
        # Filter out metadata keys starting with $ (like $description, $type) unless it's the value itself
        return {k: resolve_values(v) for k, v in node.items() if not k.startswith('$')}
    elif isinstance(node, list):
        return [resolve_values(x) for x in node]
    return node

def flatten_dict(d, parent_key='', sep='-'):
    """Flattens a dictionary into CSS variable friendly keys."""
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

def generate_css_variables(tokens):
    """Generates CSS variables for Kerala Rage tokens."""
    print(f"Generating Kerala Rage CSS variables at {CSS_OUTPUT_FILE}...")
    os.makedirs(os.path.dirname(CSS_OUTPUT_FILE), exist_ok=True)
    content = [
        "/* Kerala Rage Design Tokens */\n",
        "/* Auto-generated by scripts/build-m3-tokens.py */\n",
        "/* Do not edit this file directly */\n\n",
        ":root {\n",
    ]
    flat_tokens = flatten_dict(tokens)
    for key, value in flat_tokens.items():
        if isinstance(value, list):
            for i, item in enumerate(value):
                var_name = f"--sys-{key}-{i}"
                content.append(f"  {var_name}: {item};\n")
        else:
            var_name = f"--sys-{key}"
            content.append(f"  {var_name}: {value};\n")
    content.append("}\n")
    # Optional utility classes
    content.extend([
        "/* ===== UTILITY CLASSES ===== */\n",
        ".surface {\n",
        "  background-color: var(--md-sys-color-surface-default);\n",
        "  color: var(--md-sys-color-neutral-10);\n",
        "}\n\n",
        ".surface-container {\n",
        "  background-color: var(--md-sys-color-surface-container);\n",
        "}\n\n",
        ".primary {\n",
        "  background-color: var(--md-sys-color-primary-50);\n",
        "  color: var(--md-sys-color-primary-100);\n",
        "}\n\n",
        ".secondary {\n",
        "  background-color: var(--md-sys-color-secondary-50);\n",
        "  color: var(--md-sys-color-secondary-100);\n",
        "}\n\n",
        ".tertiary {\n",
        "  background-color: var(--md-sys-color-tertiary-50);\n",
        "  color: var(--md-sys-color-tertiary-100);\n",
        "}\n",
    ])
    with open(CSS_OUTPUT_FILE, 'w') as f:
        f.writelines(content)
    print(f"✅ Generated {len(content)} lines of CSS variables")
    return True

def generate_tailwind_patch(tokens):
    """Generates Tailwind config patch for Kerala Rage tokens."""
    print(f"Generating Tailwind patch at {TAILWIND_CONFIG_PATCH}...")
    os.makedirs(os.path.dirname(TAILWIND_CONFIG_PATCH), exist_ok=True)
    # Build Tailwind color palette
    tw_colors = {}
    colors = tokens.get('color', {})
    for color_role, tones in colors.items():
        if isinstance(tones, dict):
            tw_colors[color_role] = {
                str(tone): f"var(--md-sys-color-{color_role.replace('_', '-')}-{tone})"
                for tone, value in tones.items()
            }
        else:
            tw_colors[color_role] = f"var(--md-sys-color-{color_role.replace('_', '-')})"
    # Build Tailwind spacing scale
    tw_spacing = {
        str(name): value
        for name, value in tokens.get('spacing', {}).get('scale', {}).items()
    }
    # Build Tailwind border radius
    tw_radius = {
        name.replace('_', '-'): value
        for name, value in tokens.get('shape', {}).get('corner', {}).items()
    }
    # Build Tailwind shadows
    tw_shadows = {
        name.replace('_', '-'): value
        for name, value in tokens.get('elevation', {}).items()
    }
    # Build Tailwind font families
    tw_fonts = {
        name: [f"var(--md-sys-typescale-font-{name})"]
        for name in tokens.get('typography', {}).get('fontFamily', {}).keys()
    }
    # Build Tailwind font sizes
    tw_font_sizes = {
        name.replace('_', '-'): f"var(--md-sys-typescale-{name.replace('_', '-')}-size)"
        for name in tokens.get('typography', {}).get('size', {}).keys()
    }
    patch_content = f"""// Kerala Rage Tailwind Patch
// Auto-generated by scripts/build-m3-tokens.py
module.exports = {{
  theme: {{
    extend: {{
      colors: {json.dumps(tw_colors, indent=8)},
      spacing: {json.dumps(tw_spacing, indent=8)},
      borderRadius: {json.dumps(tw_radius, indent=8)},
      boxShadow: {json.dumps(tw_shadows, indent=8)},
      fontFamily: {json.dumps(tw_fonts, indent=8)},
      fontSize: {json.dumps(tw_font_sizes, indent=8)},
      transitionTimingFunction: {{
        'emphasized-decelerate': 'var(--md-sys-motion-easing-emphasizedDecelerate)',
        'emphasized-accelerate': 'var(--md-sys-motion-easing-emphasizedAccelerate)',
        'standard': 'var(--md-sys-motion-easing-standard)',
      }},
      transitionDuration: {{
        'short1': 'var(--md-sys-motion-duration-short1)',
        'short2': 'var(--md-sys-motion-duration-short2)',
        'medium1': 'var(--md-sys-motion-duration-medium1)',
        'long1': 'var(--md-sys-motion-duration-long1)',
      }}
    }}
  }}
}};"""
    with open(TAILWIND_CONFIG_PATCH, 'w') as f:
        f.write(patch_content)
    print("✅ Tailwind config patch generated")
    return True

def main():
    """Kerala Rage Token Builder (DTCG)"""
    print("=" * 60)
    print("Kerala Rage Token Builder (DTCG)")
    print("=" * 60)
    raw_tokens = load_tokens()
    if not raw_tokens:
        sys.exit(1)
    # Unwrap 'sys' if present
    root = raw_tokens
    if 'sys' in root:
        print("ℹ️  Unwrapping 'sys' token group.")
        root = root['sys']
    # Resolve $value references
    print("RESOLVING DTCG values...")
    tokens = resolve_values(root)
    # Filter out top-level compliance or documentation keys
    if isinstance(tokens, dict):
        tokens = {k: v for k, v in tokens.items() if k not in ['compliance', 'documentation']}
    if not tokens:
        print("❌ No tokens found after resolution")
        sys.exit(1)
    # Build outputs
    success_css = generate_css_variables(tokens)
    success_tw = generate_tailwind_patch(tokens)
    if success_css and success_tw:
        print("\n" + "=" * 60)
        print("✨ Kerala Rage token build complete!")
        print("=" * 60)
        print("\nGenerated files:")
        print(f"  1. {CSS_OUTPUT_FILE}")
        print(f"  2. {TAILWIND_CONFIG_PATCH}")
        print("\nNext steps:")
        print("  - Import CSS: Add to frontend/src/App.tsx or main.tsx")
        print("  - Merge Tailwind patch into tailwind.config.js")
        print("  - Start using tokens in components!")
    else:
        print("❌ Token build failed")

if __name__ == "__main__":
    main()
