#!/usr/bin/env python3
# scripts/build-m3-tokens.py
"""
Build M3 Expressive design tokens into CSS variables and Tailwind configuration.
Handles nested tonal palettes (color.primary.0, color.primary.10, etc.)
"""
import json
import os
import sys

# Define I/O paths
TOKEN_SOURCE_FILE = 'design-system/tokens.json'
CSS_OUTPUT_FILE = 'frontend/src/styles/m3-design-tokens.css'
TAILWIND_CONFIG_PATCH = 'design-system/tailwind-m3-patch.js'

def load_tokens():
    """Loads the M3 Expressive JSON tokens."""
    print(f"Loading M3 Expressive tokens from {TOKEN_SOURCE_FILE}...")
    if not os.path.exists(TOKEN_SOURCE_FILE):
        print(f"Error: Token source file not found at {TOKEN_SOURCE_FILE}")
        return None
    with open(TOKEN_SOURCE_FILE, 'r') as f:
        try:
            return json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error: Invalid JSON in token file. {e}")
            sys.exit(1)

def flatten_nested_dict(d, parent_key='', sep='-'):
    """Recursively flattens nested dictionaries for CSS variable names."""
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, dict):
            items.extend(flatten_nested_dict(v, new_key, sep=sep).items())
        else:
            items.append((new_key, v))
    return dict(items)

def generate_css_variables(tokens):
    """Generates CSS variables for M3 Expressive tokens."""
    print(f"Generating M3 CSS variables at {CSS_OUTPUT_FILE}...")

    os.makedirs(os.path.dirname(CSS_OUTPUT_FILE), exist_ok=True)

    content = [
        "/* M3 Expressive Design Tokens */\n",
        "/* Auto-generated by scripts/build-m3-tokens.py */\n",
        "/* Do not edit this file directly */\n\n",
        ":root {\n",
        "  /* ===== COLOR SYSTEM ===== */\n"
    ]

    # Flatten and add color tokens
    colors = tokens.get('color', {})
    for color_role, tones in colors.items():
        if isinstance(tones, dict):
            # Nested tonal palette (primary.0, primary.10, etc.)
            for tone, value in tones.items():
                var_name = f"--md-sys-color-{color_role.replace('_', '-')}-{tone}"
                content.append(f"  {var_name}: {value};\n")
        else:
            # Flat color value (outline, scrim, etc.)
            var_name = f"--md-sys-color-{color_role.replace('_', '-')}"
            content.append(f"  {var_name}: {tones};\n")

    # Add motion tokens
    content.append("\n  /* ===== MOTION SYSTEM ===== */\n")
    motion = tokens.get('motion', {})

    # Easing curves
    for easing_name, curve in motion.get('easing', {}).items():
        var_name = f"--md-sys-motion-easing-{easing_name.replace('_', '-')}"
        content.append(f"  {var_name}: {curve};\n")

    # Durations
    for duration_name, value in motion.get('duration', {}).items():
        var_name = f"--md-sys-motion-duration-{duration_name.replace('_', '-')}"
        content.append(f"  {var_name}: {value};\n")

    # Shape tokens
    content.append("\n  /* ===== SHAPE SYSTEM ===== */\n")
    shape = tokens.get('shape', {})
    for corner_type, corners in shape.items():
        if isinstance(corners, dict):
            for corner_name, value in corners.items():
                var_name = f"--md-sys-shape-{corner_type}-{corner_name.replace('_', '-')}"
                content.append(f"  {var_name}: {value};\n")

    # Spacing tokens
    content.append("\n  /* ===== SPACING SYSTEM ===== */\n")
    spacing = tokens.get('spacing', {})
    for space_name, value in spacing.get('scale', {}).items():
        var_name = f"--md-sys-spacing-{space_name}"
        content.append(f"  {var_name}: {value};\n")

    # Elevation tokens
    content.append("\n  /* ===== ELEVATION SYSTEM ===== */\n")
    elevation = tokens.get('elevation', {})
    for level_name, value in elevation.items():
        var_name = f"--md-sys-elevation-{level_name.replace('_', '-')}"
        content.append(f"  {var_name}: {value};\n")

    # Typography tokens
    content.append("\n  /* ===== TYPOGRAPHY SYSTEM ===== */\n")
    typography = tokens.get('typography', {})

    # Font families
    for family_name, value in typography.get('fontFamily', {}).items():
        var_name = f"--md-sys-typescale-font-{family_name}"
        content.append(f"  {var_name}: {value};\n")

    # Font sizes
    for size_name, value in typography.get('size', {}).items():
        var_name = f"--md-sys-typescale-{size_name.replace('_', '-')}-size"
        content.append(f"  {var_name}: {value};\n")

    # Line heights
    for lh_name, value in typography.get('lineHeight', {}).items():
        var_name = f"--md-sys-typescale-{lh_name.replace('_', '-')}-line-height"
        content.append(f"  {var_name}: {value};\n")

    # Font weights
    for weight_name, value in typography.get('weight', {}).items():
        var_name = f"--md-sys-typescale-weight-{weight_name}"
        content.append(f"  {var_name}: {value};\n")

    # Letter spacing
    for ls_name, value in typography.get('letterSpacing', {}).items():
        var_name = f"--md-sys-typescale-{ls_name.replace('_', '-')}-tracking"
        content.append(f"  {var_name}: {value};\n")

    # State layer tokens
    content.append("\n  /* ===== STATE LAYER SYSTEM ===== */\n")
    state = tokens.get('state', {})
    for state_name, values in state.items():
        if isinstance(values, dict):
            for prop, value in values.items():
                var_name = f"--md-sys-state-{state_name}-{prop.replace('_', '-')}"
                content.append(f"  {var_name}: {value};\n")

    content.append("}\n\n")

    # Add utility classes for common patterns
    content.extend([
        "/* ===== UTILITY CLASSES ===== */\n",
        ".surface {\n",
        "  background-color: var(--md-sys-color-surface-default);\n",
        "  color: var(--md-sys-color-neutral-10);\n",
        "}\n\n",
        ".surface-container {\n",
        "  background-color: var(--md-sys-color-surface-container);\n",
        "}\n\n",
        ".primary {\n",
        "  background-color: var(--md-sys-color-primary-50);\n",
        "  color: var(--md-sys-color-primary-100);\n",
        "}\n\n",
        ".secondary {\n",
        "  background-color: var(--md-sys-color-secondary-50);\n",
        "  color: var(--md-sys-color-secondary-100);\n",
        "}\n\n",
        ".tertiary {\n",
        "  background-color: var(--md-sys-color-tertiary-50);\n",
        "  color: var(--md-sys-color-tertiary-100);\n",
        "}\n\n"
    ])

    with open(CSS_OUTPUT_FILE, 'w') as f:
        f.writelines(content)

    print(f"✅ Generated {len(content)} lines of CSS variables")
    return True

def generate_tailwind_patch(tokens):
    """Generates Tailwind config patch for M3 tokens."""
    print(f"Generating Tailwind M3 patch at {TAILWIND_CONFIG_PATCH}...")

    os.makedirs(os.path.dirname(TAILWIND_CONFIG_PATCH), exist_ok=True)

    # Build Tailwind color palette
    tw_colors = {}
    colors = tokens.get('color', {})
    for color_role, tones in colors.items():
        if isinstance(tones, dict):
            # Nested tonal palette
            tw_colors[color_role] = {
                str(tone): f"var(--md-sys-color-{color_role.replace('_', '-')}-{tone})"
                for tone, value in tones.items()
            }
        else:
            # Flat color
            tw_colors[color_role] = f"var(--md-sys-color-{color_role.replace('_', '-')})"

    # Build Tailwind spacing scale
    tw_spacing = {
        str(name): value
        for name, value in tokens.get('spacing', {}).get('scale', {}).items()
    }

    # Build Tailwind border radius
    tw_radius = {
        name.replace('_', '-'): value
        for name, value in tokens.get('shape', {}).get('corner', {}).items()
    }

    # Build Tailwind shadows
    tw_shadows = {
        name.replace('_', '-'): value
        for name, value in tokens.get('elevation', {}).items()
    }

    # Build Tailwind font families
    tw_fonts = {
        name: [f"var(--md-sys-typescale-font-{name})"]
        for name in tokens.get('typography', {}).get('fontFamily', {}).keys()
    }

    # Build Tailwind font sizes
    tw_font_sizes = {
        name.replace('_', '-'): f"var(--md-sys-typescale-{name.replace('_', '-')}-size)"
        for name in tokens.get('typography', {}).get('size', {}).keys()
    }

    patch_content = f"""// M3 Expressive Tailwind Configuration Patch
// Auto-generated by scripts/build-m3-tokens.py
// Do not edit this file directly

module.exports = {{
  theme: {{
    extend: {{
      colors: {json.dumps(tw_colors, indent=8)},
      spacing: {json.dumps(tw_spacing, indent=8)},
      borderRadius: {json.dumps(tw_radius, indent=8)},
      boxShadow: {json.dumps(tw_shadows, indent=8)},
      fontFamily: {json.dumps(tw_fonts, indent=8)},
      fontSize: {json.dumps(tw_font_sizes, indent=8)},
      transitionTimingFunction: {{
        'emphasized-decelerate': 'var(--md-sys-motion-easing-emphasizedDecelerate)',
        'emphasized-accelerate': 'var(--md-sys-motion-easing-emphasizedAccelerate)',
        'standard': 'var(--md-sys-motion-easing-standard)',
      }},
      transitionDuration: {{
        'short1': 'var(--md-sys-motion-duration-short1)',
        'short2': 'var(--md-sys-motion-duration-short2)',
        'medium1': 'var(--md-sys-motion-duration-medium1)',
        'long1': 'var(--md-sys-motion-duration-long1)',
      }}
    }}
  }}
}};
"""

    with open(TAILWIND_CONFIG_PATCH, 'w') as f:
        f.write(patch_content)

    print("✅ Tailwind config patch generated")
    return True

def main():
    """Main build process."""
    print("=" * 60)
    print("M3 Expressive Design Token Builder")
    print("=" * 60)

    tokens = load_tokens()
    if not tokens:
        print("❌ Failed to load tokens")
        sys.exit(1)

    print(f"\nPreset: {tokens.get('preset', 'Unknown')}")
    print(f"Version: {tokens.get('version', 'Unknown')}")

    # Count tokens
    color_count = sum(
        len(v) if isinstance(v, dict) else 1
        for v in tokens.get('color', {}).values()
    )
    print(f"\nToken Counts:")
    print(f"  - Colors: {color_count}")
    print(f"  - Motion: {len(tokens.get('motion', {}).get('easing', {})) + len(tokens.get('motion', {}).get('duration', {}))}")
    print(f"  - Typography: {len(tokens.get('typography', {}).get('size', {}))}")
    print(f"  - Spacing: {len(tokens.get('spacing', {}).get('scale', {}))}")
    print(f"  - Elevation: {len(tokens.get('elevation', {}))}")

    print("\n" + "=" * 60)

    # Build outputs
    success_css = generate_css_variables(tokens)
    success_tw = generate_tailwind_patch(tokens)

    if success_css and success_tw:
        print("\n" + "=" * 60)
        print("✨ M3 Expressive token build complete!")
        print("=" * 60)
        print(f"\nGenerated files:")
        print(f"  1. {CSS_OUTPUT_FILE}")
        print(f"  2. {TAILWIND_CONFIG_PATCH}")
        print("\nNext steps:")
        print("  - Import CSS: Add to frontend/src/App.tsx or main.tsx")
        print("  - Merge Tailwind patch into tailwind.config.js")
        print("  - Start using tokens in components!")
    else:
        print("❌ Token build failed")
        sys.exit(1)

if __name__ == "__main__":
    main()
