#!/usr/bin/env python3
"""
generate_workflow_diagram.py

Generates Mermaid flowchart diagrams for the CareerCopilot user workflow.
Outputs Mermaid syntax to both stdout and docs/WORKFLOW_DIAGRAM.md.

Usage:
    python3 scripts/generate_workflow_diagram.py
"""

from __future__ import annotations

import os
from pathlib import Path


# ---------------------------------------------------------------------------
# Diagram definitions (Mermaid syntax)
# ---------------------------------------------------------------------------

USER_JOURNEY_DIAGRAM = """\
flowchart TD
    A([👤 User Visits CareerCopilot]) --> B{Authenticated?}

    B -- No --> C[/Login · Sign Up/]
    C --> D[(Supabase Auth)]
    D --> E([✅ Session Established])
    B -- Yes --> E

    E --> F[🏠 Dashboard]

    F --> G[📄 Upload Resume / Paste Text]
    F --> H[🔍 Paste Job URL · Description]

    G --> I[(Ingestion Service\npdfminer · python-docx)]
    H --> J[🤖 Job Analyzer Flow\nScrape + Extract Requirements]

    I --> K[(Vector Store\npgvector + Gemini Embeddings)]
    J --> L[📊 ATS Scoring Flow\nKeyword Gap Analysis]

    K --> L
    L --> M{Choose Next Action}

    M --> N[✍️ Optimise Resume\nresume_optimizer flow]
    M --> O[📝 Generate Cover Letter\nsmart_cover_letter flow]
    M --> P[🎯 Generate KSC Responses\nksc_generator flow]
    M --> Q[🏢 Research Company\ncompany_context flow]

    N --> R{Accept Suggestions?}
    R -- Yes --> S[(Save to Supabase\nDocument Store)]
    R -- No --> N

    O --> S
    P --> S
    Q --> S

    S --> T[📥 Export: PDF · DOCX · Markdown]
    T --> U[📬 Submit Application]
    U --> V[📋 Application Tracker\nKanban Board]
    V --> W([🎉 Hired!])

    style A fill:#D4A84B,color:#1A1714,stroke:#D4A84B
    style W fill:#6B7F6E,color:#F5F0E8,stroke:#6B7F6E
    style D fill:#1A1714,color:#D4A84B,stroke:#A39B8F
    style K fill:#1A1714,color:#D4A84B,stroke:#A39B8F
    style S fill:#1A1714,color:#D4A84B,stroke:#A39B8F
"""

AI_FLOW_DIAGRAM = """\
flowchart LR
    subgraph Input["📥 User Input"]
        R[Resume / Profile]
        J[Job Description / URL]
    end

    subgraph Ingestion["🔄 Ingestion Layer"]
        P[IngestionService\npdfminer · python-docx]
        JA[Job Analyzer\nScrape + NLP]
    end

    subgraph AI["🤖 AI Flows  ·  Gemini via Genkit"]
        ATS[ATS Scoring\nats_scoring.py]
        RO[Resume Optimizer\nresume_optimizer.py]
        CL[Cover Letter Generator\ncover_letter_generator.py]
        KSC[KSC Generator\nksc_generator.py]
        CC[Company Context\ncompany_context.py]
        JM[Job Matcher\nadvanced_job_matching.py]
    end

    subgraph Store["🗄️ Data Layer"]
        VS[(Vector Store\npgvector)]
        DB[(Postgres\nSupabase)]
    end

    subgraph Output["📤 Output"]
        OD[Optimised Resume]
        OCL[Cover Letter]
        OKSC[KSC Responses]
        OA[Application Package]
    end

    R --> P --> VS
    J --> JA --> ATS
    VS --> ATS
    ATS --> RO & CL & KSC & CC & JM
    RO --> OD --> DB
    CL --> OCL --> DB
    KSC --> OKSC --> DB
    OD & OCL & OKSC --> OA

    style AI fill:#1A1714,color:#F5F0E8,stroke:#D4A84B
    style Store fill:#1A1714,color:#F5F0E8,stroke:#A39B8F
    style Input fill:#2A1F0B,color:#F5F0E8,stroke:#D4A84B
    style Output fill:#0B2A1A,color:#F5F0E8,stroke:#6B7F6E
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

def build_markdown(user_journey: str, ai_flow: str) -> str:
    """Compose the full docs/WORKFLOW_DIAGRAM.md content."""
    return f"""\
# CareerCopilot – Workflow Diagrams

> Generated by `scripts/generate_workflow_diagram.py`.
> Render with any Mermaid-compatible viewer (GitHub, mermaid.live, VS Code extension).

---

## 1. User Journey

End-to-end flow from landing on the app through to submitting a job application.

```mermaid
{user_journey.strip()}
```

---

## 2. AI Flow Architecture

How the Genkit AI flows connect inputs, vector storage, and generated outputs.

```mermaid
{ai_flow.strip()}
```

---

## Key Components

| Component | File | Responsibility |
|---|---|---|
| Ingestion Service | `backend/app/services/ingestion_service.py` | Parse PDF/DOCX resumes |
| Job Analyzer | `ai/flows/backend/job_analyzer.py` | Scrape & extract job requirements |
| ATS Scoring | `ai/flows/backend/ats_scoring.py` | Score resume against job description |
| Resume Optimizer | `ai/flows/backend/resume_optimizer.py` | Suggest keyword improvements |
| Cover Letter Generator | `ai/flows/backend/cover_letter_generator.py` | Draft tailored cover letters |
| KSC Generator | `ai/flows/backend/ksc_generator.py` | Draft STAR-format KSC responses |
| Company Context | `ai/flows/backend/company_context.py` | Research company background |
| Vector Store | `backend/app/services/vector_store.py` | Semantic search (pgvector) |
| Application Tracker | `frontend/src/features/applications/` | Kanban board for job tracking |
"""


def main() -> None:
    user_journey = USER_JOURNEY_DIAGRAM
    ai_flow = AI_FLOW_DIAGRAM

    markdown = build_markdown(user_journey, ai_flow)

    # Write to docs/WORKFLOW_DIAGRAM.md
    repo_root = Path(__file__).resolve().parent.parent
    output_path = repo_root / "docs" / "WORKFLOW_DIAGRAM.md"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(markdown, encoding="utf-8")

    print(f"✅  Workflow diagram written to: {output_path.relative_to(repo_root)}")
    print()
    print("--- User Journey (Mermaid) ---")
    print(user_journey)
    print("--- AI Flow Architecture (Mermaid) ---")
    print(ai_flow)


if __name__ == "__main__":
    main()
