"""Add resume_audits table

Revision ID: 9fed372f36f6
Revises: ea364f0feefd
Create Date: 2026-03-06 06:55:03.021876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9fed372f36f6'
down_revision: Union[str, None] = 'ea364f0feefd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_audits',
    sa.Column('user_id', sa.String(length=36), nullable=True, comment='Reference to the user who ran the audit'),
    sa.Column('resume_hash', sa.Text(), nullable=False, comment='Hash of the resume audited to detect duplicates'),
    sa.Column('audit_result', sa.JSON(), nullable=False, comment='The output from the AI audit flow'),
    sa.Column('strictness_mode', sa.String(length=50), nullable=False, comment='Rule strictness mode applied'),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True, comment='Time taken to process in milliseconds'),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_audits_id'), 'resume_audits', ['id'], unique=False)
    op.create_index(op.f('ix_resume_audits_resume_hash'), 'resume_audits', ['resume_hash'], unique=False)
    op.create_index(op.f('ix_resume_audits_user_id'), 'resume_audits', ['user_id'], unique=False)
    with op.batch_alter_table('document_embeddings') as batch_op:
        batch_op.drop_index('ix_document_embeddings_id')
        batch_op.drop_index('ix_document_embeddings_user_id')
    op.drop_table('document_embeddings')

    # SQLite doesn't support dropping constraints easily, ignore cache fk change for now

    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('metadata', sa.JSON(), nullable=True, comment='Additional user metadata (e.g., career_profile, career_database)'))
        batch_op.drop_column('hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('metadata')
    op.create_table('document_embeddings',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.VARCHAR(), nullable=False),
    sa.Column('embedding', sqlite.JSON(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_document_embeddings_user_id', 'document_embeddings', ['user_id'], unique=False)
    op.create_index('ix_document_embeddings_id', 'document_embeddings', ['id'], unique=False)
    op.drop_index(op.f('ix_resume_audits_user_id'), table_name='resume_audits')
    op.drop_index(op.f('ix_resume_audits_resume_hash'), table_name='resume_audits')
    op.drop_index(op.f('ix_resume_audits_id'), table_name='resume_audits')
    op.drop_table('resume_audits')
    # ### end Alembic commands ###
