# .github/workflows/firebase-ci.yml

name: Build and Test Firebase Project

# This workflow runs on pushes to the main branch and any pull request targeting main.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# Enforces read-only permissions for the GITHUB_TOKEN to enhance security.
permissions:
  contents: read

jobs:
  build_and_test:
    name: Build, Audit & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Yarn Cache Directory Path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache Node Modules
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Scan for Vulnerabilities
        run: yarn audit

      - name: Run Tests
        run: yarn test
