name: CD - Deploy to Staging and Production

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-staging:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v5
      - name: Deploy Frontend to Staging
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAREERCOPILOT_STAGING }}'
          channelId: live
          projectId: careercopilot-staging
          target: careercopilot-staging-frontend
      - name: Deploy Backend to Staging
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: careercopilot-backend-staging
          project_id: ${{ secrets.GCP_STAGING_PROJECT_ID }}
          credentials: ${{ secrets.GCP_STAGING_SA_KEY }}
          region: us-central1
          source: ./backend

  deploy-production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v5
      - name: Deploy Frontend to Production
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAREERCOPILOT }}'
          channelId: live
          projectId: careercopilot-prod
          target: careercopilot-prod-frontend
      - name: Deploy Backend to Production
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: careercopilot-backend-prod
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          region: us-central1
          source: ./backend
