# This is the name of the GitHub Actions workflow.
name: CD - Deploy to Staging and Production

# This workflow is triggered on any push to the 'develop' or 'main' branches.
on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: 'Debug: List Files in Frontend Directory'
        run: ls -laR frontend/

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Deploy Frontend to Firebase Hosting (Staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAREERCOPILOT_STAGING }}'
          projectId: '${{ secrets.GCP_STAGING_PROJECT_ID }}'
          entryPoint: ./frontend

      - name: Authenticate to Google Cloud (Staging)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_STAGING_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Install Backend Dependencies
        run: pip install -r backend/requirements.txt

      - name: Build and Push Docker Image (Staging)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_STAGING_PROJECT_ID }}/careercopilot-repo/backend:${{ github.sha }}

      - name: Deploy Backend to Cloud Run (Staging)
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: 'careercopilot-backend-staging'
          region: 'australia-southeast2'
          image: australia-southeast1-docker.pkg.dev/${{ secrets.GCP_STAGING_PROJECT_ID }}/careercopilot-repo/backend:${{ github.sha }}
          env_vars: |
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            # ... Add all other runtime secrets here ...

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend

      - name: Deploy Frontend to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CAREERCOPILOT }}'
          projectId: '${{ secrets.GCP_PROJECT_ID }}'
          entryPoint: ./frontend

      - name: Authenticate to Google Cloud (Production)
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Install Backend Dependencies
        run: pip install -r backend/requirements.txt

      - name: Build and Push Docker Image (Production)
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: australia