name: Build and Deploy Backend to Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-push-and-deploy:
    name: Build, Push, and Deploy to Cloud Run
    runs-on: ubuntu-latest
    
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ secrets.GCP_WIF_PROVIDER }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: 'careercopilot-staging'

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |-
          gcloud builds submit ./backend \
            --tag us-central1-docker.pkg.dev/careercopilot-staging/careercopilot-repo:latest \
            --project=careercopilot-staging
            
      - name: Deploy to Cloud Run with Secret
        run: |-
          gcloud run deploy careercopilot-backend-staging \
            --image us-central1-docker.pkg.dev/careercopilot-staging/careercopilot-repo:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --set-secrets=GEMINI_API_KEY=GEMINI_API_KEY:latest \
            --project=careercopilot-staging
