name: Frontend Unit Tests

on:
  push:
    branches: [ main, develop, chromebook ]
  pull_request:
    branches: [ main, develop ]

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Run Frontend Tests
        working-directory: ./frontend
        run: yarn test:ci
